config/routes.rb
Rails.application.routes.draw do

	resources :loans

	resources :deposits

  	devise_for :users

  	get 'accounts', to: "home#accounts" , as: :accounts 

  	get 'accounts/:id', to: "home#show", as: :account
  	
  	root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :loans, dependent: :destroy
   has_many :deposits, dependent: :destroy

   	def username 
   		return self.email.split('@')[0].capitalize
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController

	def new
		@deposit = Deposit.new
	end

	def create 
		@deposit = Deposit.new(params.require(:deposit).permit(:debit))
		@deposit.user = current_user
		@deposit.save
		redirect_to account_path(current_user)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def accounts
  	@users = User.all
  	@deposits = Deposit.all
  	@loans = Loan.all
  end

  def show
  	@user = User.find(params[:id])
  	@deposits = Deposit.all
  	@loans = Loan.all
  	# @calculate = Calculate.new(Loan.all, Deposit.all, current_user)
  end

  
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController

	before_action :authenticate_user!

	def index

	end

	def new
		@loan =Loan.new
	end

	def create
		@loan =Loan.new(set_params)
		@loan.user = current_user
		@loan.save
		redirect_to account_path(current_user)
	end

	def show
	end

	private

	def set_params
		params.require(:loan).permit(:credit)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/deposits/new.html.erb
<%= form_with model: @deposit do |f| %>
	<%= f.number_field :debit %>
	<%= f.submit %>
<% end %>

app/views/home/accounts.html.erb
	<table cellpadding="10px">
		<tr>
			<th>Account Holder</th>
			<th>Amount</th>
			<th></th>
		</tr>

		<% @users.each do |user| %>
			<tr>
				<% if user == current_user %>

				<td><%= user.username %></td>
				<td>
					<% total_deposit = 0 %>
					<% total_loan  = 0 %>
					<% @loans.each do |loan| %>
						<% if loan.user == current_user%>
						<% total_loan += loan.credit %>
						<% end %>
					<% end %>

					<% @deposits.each do |deposit| %>
					<% if deposit.user == current_user %>
						<% total_deposit += deposit.debit %>
					<% end %>
					<% end %>
					<%= total_deposit - total_loan %>
				</td>
				<td><%= link_to "View", account_path(user) %></td>
				<% end %>
			</tr>
		<% end %>
	</table>
<hr>
<%= link_to "Back", root_path %>

app/views/home/index.html.erb
<% if !current_user %>
	<%= link_to "Sign In", new_user_registration_path %>
	<%= link_to "Log In", new_user_session_path %>
<% else %>
	<h3><%= current_user.username %>'s Bank Account </h3>
	<%= link_to "View Account", accounts_path %>
	<hr>
	<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<% end %>

app/views/home/show.html.erb
<h3>This account belongs to</h3>
<h2><%= @user.username %></h2>
<hr>

<%= link_to "Create Loan", new_loan_path %><br>
<%= link_to "Create Deposit", new_deposit_path %>
<hr>
<h4>Total Amount</h4>
	<% total_deposit = 0 %>
	<% total_loan  = 0 %>
	<% @loans.each do |loan| %>
		<% if loan.user == current_user%>
			<% total_loan += loan.credit %>
		<% end %>
	<% end %>

	<% @deposits.each do |deposit| %>
		<% if deposit.user == current_user %>
			<% total_deposit += deposit.debit %>
		<% end %>
	<% end %>

	Rs <%= total_deposit - total_loan %>
<hr>


<h4>All Loan </h4>
<% @loans.each do |loan| %>
	<% if loan.user == current_user %>
		<b><%= loan.created_at.strftime("%B %e, %Y at %H:%M:%S") %>: </b>
		 <i>Rs.<%= loan.credit %></i> by
		 <u> <%= loan.user.username %></u> <br>
	<% end %>
<% end %>

<hr>

<h4>All Deposits </h4>
<% @deposits.each do |deposit| %>
	<% if deposit.user == current_user %>
		<b><%= deposit.created_at.strftime("%B %e, %Y at %H:%M:%S") %>: </b>
		 <i>Rs.<%= deposit.debit %></i> by
		 <u> <%= deposit.user.username %></u> <br>
	<% end %>
<% end %>

<hr>
<%= link_to "Back", accounts_path %>

app/views/layouts/_alert.html.erb
    <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/alert' %>
    <h1>Millennium Bank</h1>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/loans/new.html.erb
<h3>This account belongs to</h3>
<h2><%= current_user.username %></h2>
<hr>

<%= form_with model: @loan do |f| %>
	<%= f.number_field :credit %>
	<%= f.submit %>
<% end %>